---

- include_tasks: requirements.yml
  tags: [ "jboss:amq:requirements" ]

- name: Install - Download AMQ from RHN
  include_tasks: rhel_url.yml
  when: transfer_method == 'csp-to-host' and jboss_amq_exists.stat.exists == false

- name: Install - Copy AMQ from controller    
  include_tasks: copy_from_controller.yml
  when: transfer_method == 'copy-from-controller' and jboss_amq_exists.stat.exists == false

- include_tasks: install.yml
  tags: [ "jboss:amq:install" ]
  become: yes
  become_user: "{{ amq_user }}"
  become_method: sudo

- include_tasks: configure.yml
  tags: [ "jboss:amq:configure" ]
  become: yes
  become_user: "{{ amq_user }}"
  become_method: sudo

- include_tasks: patch.yml
  tags: [ "jboss:amq:patch" ]
  become: yes
  become_user: "{{ amq_user }}"
  become_method: sudo
  when: amq_broker_patch
